name: stable version test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Unit test
        run: ./vendor/bin/phpunit
        env:
          DATABASE_HOST: 'localhost'
          DATABASE_DBNAME: 'postgres'
          DATABASE_USER: 'postgres'
          DATABASE_PASSWORD: 'postgres'
