name: stable version test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json
        run: composer validate

      - name: Install dependencies
        run: composer install

      - name: Unit test
        run: ./vendor/bin/phpunit
