name: matrix test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

strategy:
  matrix:
    symfony: ['4.1.*', '4.2.*', '4.3.*', '4.4.*', '5.0.*']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install specific symfony version
        run: composer require
          symfony/property-access:${{ matrix.symfony }}
          symfony/property-info:${{ matrix.symfony }}
          symfony/serializer:${{ matrix.symfony }}
          symfony/framework-bundle:${{ matrix.symfony }}
          symfony/expression-language:${{ matrix.symfony }}

      - name: Install all dependencies
        run: composer install

      - name: Unit test
        run: ./vendor/bin/phpunit
