name: test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  stable_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.0

      - name: Validate composer.json
        run: composer validate

      - name: Lint
        run: composer lint

      - name: Unit test
        run: ./vendor/bin/phpunit
        env:
          DATABASE_HOST: 'localhost'
          DATABASE_DBNAME: 'postgres'
          DATABASE_USER: 'postgres'
          DATABASE_PASSWORD: 'postgres'

  matrix_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        symfony: ['4.4.*', '5.3.*', '5.4.*', '6.0.*']
        php: ['8.0']

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: 'postgres'
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Install specific symfony version
        run: composer require
          symfony/property-access:${{ matrix.symfony }}
          symfony/property-info:${{ matrix.symfony }}
          symfony/serializer:${{ matrix.symfony }}
          symfony/framework-bundle:${{ matrix.symfony }}
          symfony/expression-language:${{ matrix.symfony }}

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: Unit test
        run: ./vendor/bin/phpunit
        env:
          DATABASE_HOST: 'localhost'
          DATABASE_DBNAME: 'postgres'
          DATABASE_USER: 'postgres'
          DATABASE_PASSWORD: 'postgres'
